name: Production Builds
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Extract version number
        id: extract_version
        run: echo "TAG_NAME=$(echo ${{ github.ref }} | cut -d'/' -f3)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

                    

      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1


      # This will decode the keystore from base 64 text representation that we have stored in secrets
      # and generates and keystore file and gets stored in /android-app path
      - name: Decode keystore and create jks
        run: echo "${{ secrets.SIGNINGKEYBASE64 }}" | base64 --decode > keystore.jks


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release apk
        run: ./gradlew assembleRelease -Pversion=$TAG_NAME

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
    
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Signed app bundle
        uses: actions/upload-artifact@v2
        with:
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          
      - name: Rename File
        run: |
          mv ${{steps.sign_app.outputs.signedReleaseFile}} app/build/outputs/apk/release/Harmonify.apk
      
      - name: Upload To Github Release
        uses: xresloader/upload-to-github-release@v1.5.0
        env:
           GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
           file: app/build/outputs/apk/release/Harmonify.apk
           tags: true
           draft: false
